"""第30章「TENXの外側」:filings / xbrl_facts / alerts / macro_series の新設と
tickers.cik の追加(30.3.5・30.5.2・30.7.4・30.8.2)。

4テーブルをまとめて1回のマイグレーションにしたのは、いずれもモデル定義
(db/models.py)への追加を1回のコミットで行ったため——down_revisionの
チェーンを4段に分けても意味のある中間状態が無い(どのテーブルも他の
フェーズのコードから参照されて初めて使われる)。

Revision ID: 3c09c1812341
Revises: c604d4482fc2
Create Date: 2026-08-28 08:18:53.440348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c09c1812341'
down_revision: Union[str, Sequence[str], None] = 'c604d4482fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.String(length=30), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'observation_date', name='uq_macro_series_date')
    )
    op.create_index(op.f('ix_macro_series_observation_date'), 'macro_series', ['observation_date'], unique=False)
    op.create_index(op.f('ix_macro_series_series_id'), 'macro_series', ['series_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('triggered_on', sa.Date(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'code', 'triggered_on', name='uq_alert_ticker_code_date')
    )
    op.create_index(op.f('ix_alerts_ticker_id'), 'alerts', ['ticker_id'], unique=False)
    op.create_index('ix_alerts_triggered', 'alerts', ['triggered_on'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_document', sa.String(length=200), nullable=True),
    sa.Column('document_url', sa.String(length=400), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'accession_number', name='uq_filing_ticker_accession')
    )
    op.create_index(op.f('ix_filings_filed_date'), 'filings', ['filed_date'], unique=False)
    op.create_index('ix_filings_form_filed', 'filings', ['form', 'filed_date'], unique=False)
    op.create_index('ix_filings_ticker_filed', 'filings', ['ticker_id', 'filed_date'], unique=False)
    op.create_index(op.f('ix_filings_ticker_id'), 'filings', ['ticker_id'], unique=False)
    op.create_table('xbrl_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.String(length=20), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'tag', 'period_end', 'form', 'accession_number', name='uq_xbrl_fact')
    )
    op.create_index(op.f('ix_xbrl_facts_filed_date'), 'xbrl_facts', ['filed_date'], unique=False)
    op.create_index(op.f('ix_xbrl_facts_ticker_id'), 'xbrl_facts', ['ticker_id'], unique=False)
    op.create_index('ix_xbrl_facts_ticker_tag_end', 'xbrl_facts', ['ticker_id', 'tag', 'period_end'], unique=False)
    # 注:autogenerateは 'universe_bak_ch29' / 'scores_bak_ch29'(29章移行時の
    # 手動バックアップテーブル、models.pyに対応クラスが無い)の削除も提案したが、
    # このマイグレーションの関心事(30章の新テーブル追加)とは無関係のため
    # 意図的に除外した。バックアップの要否は別途判断する。
    op.add_column('tickers', sa.Column('cik', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_tickers_cik'), 'tickers', ['cik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickers_cik'), table_name='tickers')
    op.drop_column('tickers', 'cik')
    op.drop_index('ix_xbrl_facts_ticker_tag_end', table_name='xbrl_facts')
    op.drop_index(op.f('ix_xbrl_facts_ticker_id'), table_name='xbrl_facts')
    op.drop_index(op.f('ix_xbrl_facts_filed_date'), table_name='xbrl_facts')
    op.drop_table('xbrl_facts')
    op.drop_index(op.f('ix_filings_ticker_id'), table_name='filings')
    op.drop_index('ix_filings_ticker_filed', table_name='filings')
    op.drop_index('ix_filings_form_filed', table_name='filings')
    op.drop_index(op.f('ix_filings_filed_date'), table_name='filings')
    op.drop_table('filings')
    op.drop_index('ix_alerts_triggered', table_name='alerts')
    op.drop_index(op.f('ix_alerts_ticker_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_macro_series_series_id'), table_name='macro_series')
    op.drop_index(op.f('ix_macro_series_observation_date'), table_name='macro_series')
    op.drop_table('macro_series')
    # ### end Alembic commands ###
