"""initial schema

Revision ID: 6d24bcc6222c
Revises: 
Create Date: 2026-08-23 22:47:26.366622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d24bcc6222c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('collection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_logs_run_id'), 'collection_logs', ['run_id'], unique=False)
    op.create_index('ix_collection_logs_run_status', 'collection_logs', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_collection_logs_ticker_id'), 'collection_logs', ['ticker_id'], unique=False)
    op.create_table('forward_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=10), nullable=False),
    sa.Column('realized_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'base_date', 'horizon', name='uq_forward_return')
    )
    op.create_index(op.f('ix_forward_returns_base_date'), 'forward_returns', ['base_date'], unique=False)
    op.create_index(op.f('ix_forward_returns_ticker_id'), 'forward_returns', ['ticker_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'trade_date', name='uq_price_ticker_date')
    )
    op.create_index(op.f('ix_price_snapshots_ticker_id'), 'price_snapshots', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_price_snapshots_trade_date'), 'price_snapshots', ['trade_date'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_date', sa.Date(), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_snapshots_content_hash'), 'raw_snapshots', ['content_hash'], unique=False)
    op.create_index('ix_raw_snapshots_ticker_date', 'raw_snapshots', ['ticker_id', 'snapshot_date'], unique=False)
    op.create_index(op.f('ix_raw_snapshots_ticker_id'), 'raw_snapshots', ['ticker_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('scoring_version', sa.String(length=20), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('subscores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_ratio', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'score_date', 'scoring_version', name='uq_score_ticker_date_version')
    )
    op.create_index(op.f('ix_scores_score_date'), 'scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_scores_ticker_id'), 'scores', ['ticker_id'], unique=False)
    op.create_table('ticker_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'effective_from', name='uq_alias_symbol_effective_from')
    )
    op.create_index(op.f('ix_ticker_aliases_ticker_id'), 'ticker_aliases', ['ticker_id'], unique=False)
    op.create_table('universe_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'ticker_id', name='uq_universe_snapshot_date_ticker')
    )
    op.create_index(op.f('ix_universe_snapshots_snapshot_date'), 'universe_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_universe_snapshots_ticker_id'), 'universe_snapshots', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universe_snapshots_ticker_id'), table_name='universe_snapshots')
    op.drop_index(op.f('ix_universe_snapshots_snapshot_date'), table_name='universe_snapshots')
    op.drop_table('universe_snapshots')
    op.drop_index(op.f('ix_ticker_aliases_ticker_id'), table_name='ticker_aliases')
    op.drop_table('ticker_aliases')
    op.drop_index(op.f('ix_scores_ticker_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_score_date'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_raw_snapshots_ticker_id'), table_name='raw_snapshots')
    op.drop_index('ix_raw_snapshots_ticker_date', table_name='raw_snapshots')
    op.drop_index(op.f('ix_raw_snapshots_content_hash'), table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index(op.f('ix_price_snapshots_trade_date'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_ticker_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_forward_returns_ticker_id'), table_name='forward_returns')
    op.drop_index(op.f('ix_forward_returns_base_date'), table_name='forward_returns')
    op.drop_table('forward_returns')
    op.drop_index(op.f('ix_collection_logs_ticker_id'), table_name='collection_logs')
    op.drop_index('ix_collection_logs_run_status', table_name='collection_logs')
    op.drop_index(op.f('ix_collection_logs_run_id'), table_name='collection_logs')
    op.drop_table('collection_logs')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    # ### end Alembic commands ###
