"""add subscore_fallback to scores

Revision ID: 805471bbebdb
Revises: 6d24bcc6222c
Create Date: 2026-08-24 11:23:27.329735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '805471bbebdb'
down_revision: Union[str, Sequence[str], None] = '6d24bcc6222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('subscore_fallback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'subscore_fallback')
    # ### end Alembic commands ###
