"""v4 moic model: calibration map and on-pace probability

Revision ID: c604d4482fc2
Revises: d5a91c3e6b74
Create Date: 2026-08-26 00:29:41.609548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c604d4482fc2'
down_revision: Union[str, Sequence[str], None] = 'd5a91c3e6b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('calibration_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('backtest_runs', sa.Column('asset_correlation', sa.Numeric(precision=6, scale=5), nullable=True))
    op.add_column('scores', sa.Column('calibrated_on_pace_probability', sa.Numeric(precision=10, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'calibrated_on_pace_probability')
    op.drop_column('backtest_runs', 'asset_correlation')
    op.drop_column('backtest_runs', 'calibration_map')
    # ### end Alembic commands ###
